### ISSUE TITLE
hi,my friend. what is going on? i have download your mebedding file,https://drive.google.com/file/d/1-R_2lqS5AQtWqLZXC45SrfkK5XETREe5/view?usp=sharing

### ISSUE THREAD

**Issue by daima2017** [amzn/ss-aga-kgc#4]
![image](https://user-images.githubusercontent.com/44838048/169842685-451cce0b-d8a1-4feb-8122-dcd5ca91ab19.png)
hi,my friend. what is going on? i have download your mebedding file from,https://drive.google.com/file/d/1-R_2lqS5AQtWqLZXC45SrfkK5XETREe5/view?usp=sharing

**Comment by daima2017** [comment]
![image](https://user-images.githubusercontent.com/44838048/169848145-5e752e39-8b1d-444d-81c1-9efdec717f20.png)

**Comment by daima2017** [comment]
2022-05-23 22:28:21,405 INFO     Namespace(alias='run', align_lr=0.001, align_margin=6, batch_size=200, burin_in_epoch=15, clip=10, data_path='dataset/', dataset='dbp5l', device=device(type='cuda', index=0), dim=256, dropout=0.1, encoder_hdim_align=256, encoder_hdim_kg=256, entity_dim=256, epoch10=3, epoch11=2, epoch2=2, generation_freq=5, k=10, k_csls=3, l2=0, load=None, lr=0.01, n_heads=1, n_layers_KG=2, n_layers_align=2, num_entities=169767, num_hop=2, num_kgs=15, num_relations=14415, optimizer='AdamW', preserved_ratio=0.1, reg_scale=1e-05, relation_dim=256, round=25, target_language='ja', transe_margin=0.3, use_default=True, val_freq=1)
Traceback (most recent call last):
  File "D:/myexperiment/EntityAlign/13-KGC4EA/ss-aga-kgc-main2/run_model.py", line 407, in <module>
    main(parse_args())
  File "D:/myexperiment/EntityAlign/13-KGC4EA/ss-aga-kgc-main2/run_model.py", line 280, in main
    model = SSAGA(args, entity_bert_emb, args.num_relations, args.num_entities, args.num_kgs).to(args.device)
  File "D:\myexperiment\EntityAlign\13-KGC4EA\ss-aga-kgc-main2\src\ssaga_model.py", line 113, in __init__
    assert entity_bert_emb.shape[0] == num_entities
AssertionError

**Comment by ZijieH** [comment]
The original data from https://github.com/stasl0217/KEnS contains an entity file de.tsv that is not used in the code. So you need to first remove it.
